services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566' # LocalStack endpoint
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './volume:/var/lib/localstack'